name = "harmonic-imo-2025"
version = "0.1.0"
keywords = ["aristotle"]
defaultTargets = ["HarmonicLean"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.20.0-rc5"

[[lean_lib]]
name = "HarmonicLean"
